---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: navidrome
  namespace: navidrome
spec:
  encryptedData:
    passwordEncryptionKey: AgBtlmMcccUuIGQrpitKckpxRxcLu0w3rbDns/2N7UeLcq6S06okJEAdMW7wF2KvTfXfGCZGqY+j863NtGLrjMf3TpaeJdoIyQfjfB7phMD1jI1NN8rPVyX8i3dx1kjnR9fe3QoriPTqb81BEdQpwfVKqYDiKXD4E4+RZG4WH4c8rW2sL3XTRSLytsVt5bWrzG6o5Mh7h5svptAMgTvrqAfMSSOYJhk5xQntSbdNWUCPpvOEnltUSs+Hmp7XLSGkM+6QohR0dOkr4m46Xyb2UBU08sdGXqU6WNFPYuLHdjdn6mdU9hQyMUqexwKjQuhDUGMU11ykhi9RkkY+Al0PHHqLTFXREcwFa6/UrypnGJPgAzlomRucoN5dc8ntpMtmSA6Fp0UdKm4iCQG3ocYj97E1oANZCoDXDA/79XReTFdYHfhkd+l5MOtb9saMbn9h5C5mpycxiHywm/MBDa9XYYOP7lMTk+8WWiskPOK6e+5K6z4maPrAe/9zuYncoKMPJHn9ycKzOxF8UM5brTWzXTemOuwzHzEVoWqtE/5YefcUePw6+UmkFzxPb20o8XLDd57++QozT/R386aHjyHQIPG0pan8p/U1YRCJjjSGAp8jYNuTR4xvqk3FAjrQSKRwUHUDVoiO+vtbqQVBaBprxyMTppegogx1siX5zxOQiaM/WaVeWqJO7ee14V/wDUla2i5FbHvpOMPPyK7vTVPkBrMrC4e4BhXV79Z8m50IHytqaUmXg7ggaKztQsThkK4Blr+oRA==
  template:
    metadata:
      creationTimestamp: null
      name: navidrome
      namespace: navidrome
