apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-media-backup
  namespace: media
spec:
  schedule: '0 30 2 * * *'
  backupOwnerReference: self
  cluster:
    name: postgres-media
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
