apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-backup
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 0 2 * * *
  groups:
    - default
  name: daily-backup
  retain: 3
  task: backup
