---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: meilisearch-master-key
  namespace: linkwarden
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgBftUB5mzfWROJv0u0FT613U6uK36lDNjGa1BewLQacgv8exygugB3Ls0lZb45omkpwoCW65mBTj4iYdH7QNmwXn1NyRl+YxqAWTong05e1+tFLLG7Pg3Egf971i2eKGvHEWMIQ3E1t3UqD9yYSzwfrzmzEGYOSByFRVYzoPSXShLTToS0ixGf4IgY795QLO8zYaJAIannPu3yeDzSdMPlO4qLNzi+rbboziyfWtqtVv8TD0fw/GAO2klHCgdVmKpV04I4YXW8ciuR4yMfh6PM3CO6Da929QkEpv6k+frLrVbcaEvHkd07itaqwiV/EpnQ34aLGNlWeDREYU856mzOWwleZZEzjFrcSyzbGcUov3iITgvL5bL+1pb2jSkU33pwBE8RBN4mw0sygqW4QmQAJV61iFTs02gmi9KslsrwpdZDQ36bIfHxwP9sFUO1oVr/2kOTAa+Qr9zzbwcNiGNDk2n3I+pfShbPI0Q8hPr6Dq9CpJL/4aS+2G/wq+u3ioknuNY0hlSxyaqcyxkuoFy5Lz0Mq85odv5KTjMaa2j4t4qKrY6f3xBCMrsgTDefm+cOLnI/k7ZefaC+gUYEqvKipTgRmzFIl30B4JDDmQH4N2oUfmgpgDnkc1pZ6PV4YAVuAvhc5GnO6oqIeRvxo9GhbEGI0rTHHSHCcAVD0whsUnD8rsBGy19imvDc1GQS4MMB0EaK+D8GZUEnyd2Gc3nSkz9xlQT3iabUyEoYesxvwETeVgTxh/y8t1Oo1Iw==
  template:
    metadata:
      creationTimestamp: null
      name: meilisearch-master-key
      namespace: linkwarden
    type: Opaque
