apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-linkwarden
  namespace: linkwarden
  annotations:
    argocd.argoproj.io/sync-wave: '-50'
    glance/parent: linkwarden
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.10-standard-trixie@sha256:0672b63296ff64d0911598ae0680d433ebbffd17d22c3bd04cb5b383fb808d0d
  storage:
    storageClass: topolvm-provisioner
    size: 1Gi
  postgresql:
    parameters:
      shared_buffers: '128MB'
    synchronous:
      method: any
      number: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 512Mi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-homelab
