longhornManager:
  tolerations:
    - key: node-role.kubernetes.io/storage
      operator: Exists
      effect: NoSchedule

longhornDriver:
  tolerations:
    - key: node-role.kubernetes.io/storage
      operator: Exists
      effect: NoSchedule

defaultSettings:
  taintToleration: node-role.kubernetes.io/storage:NoSchedule
  createDefaultDiskLabeledNodes: true
  defaultReplicaCount: '{"v1": "2", "v2": "2"}'

persistence:
  defaultClassReplicaCount: 2
  defaultClass: true

defaultBackupStore:
  backupTarget: s3://longhorn-luna@homelab/
  backupTargetCredentialSecret: s3-secret
