apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ""
    argocd.argoproj.io/sync-wave: "5"
  creationTimestamp: null
  name: alertmanager-receivers
  namespace: monitoring
spec:
  encryptedData:
    healthchecks-io-url: AgAx5wE6xfJTOcHSCOSJoUk62fShguxKE7cZmN9DqNwUeawrQ2jMal98ZcyIeuRoSsh6G8pednc4+o6zQNh5slse0Q2xPqbreYAvcDlLeFxGfsxBXv0ZVY73VfYfNcBXqfHhu6+6qakgLKfUqzFBTZ9CAjH1vhEyjWkrv5FAL+zkBZoXY7FCxo97oiNUEvIG+LcmtRRmwZQBJgbja466WUA2o78QOvocIQ1p9qIVgUQBS6+vUjNNTXTvSsyUgQrZqvFOesT4W61KATcJEPWqIxvw/ljOC0gz8kH6Nja0BtkCzjCRR5VZt2gwIe6iR1Y+pBqVk2DywD8IsCUzj3+J7qMT5w2OU5UYgQM7vUaSEj88jTlEB915NaH6LgKfNa3ec1o+2ZwFhuX6u2y0MQPWRA+AV/9toex+29gwjTzkuu54Xtg6XpShH/lLBT6pWg3ySNENlOFiAm27kHWWhaORzMrZA1UOSkSoes6hixSFzP9zwS6I9ZrH73js88gX0hAYgo640CnYAhGNw+pawTTwvZXApTBYJtko3bpY52BlYq4KXpeYZgTER8XLok73qdyRC4hAV7FhENuv9UtNW3/7FbDoOSmAXeO0QPHzrkE10epJ4l0++kJhDs8tR3kXXMGC/XjQv1hzH9JFD2cudVQe7KQyo8GRIkgGJdUdf+dOGXmugvSCopXlGm8dDsPkVtdMWn1rTVzvWsYnYRYS9n2ZuLFr2kUYajlWlL7pn+pgCL5qnGhrAR65TmP4anpOz8s3jgyLK6w3+WkIVw==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-receivers
      namespace: monitoring
    type: Opaque
