# Default values for unbound.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: mvance/unbound
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.22.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: 10.10.100.1
  port: 53

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: {}

affinity: {}

config: |
  server:
    username: "_unbound"

    directory: "/opt/unbound/etc/unbound"
    chroot: "/opt/unbound/etc/unbound"

    logfile: ""
    use-syslog: no
    log-queries: yes

    do-daemonize: no

    # Necessary for DNSSEC
    auto-trust-anchor-file: "var/root.key"

    tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt

    interface: 0.0.0.0@53
    interface: ::0@53

    access-control: 127.0.0.0/32 allow
    access-control: 172.18.0.0/12 allow
    access-control: 10.0.0.0/8 allow

    private-address: 10.0.0.0/8

    # Tailscale CIDR range
    private-address: 100.64.0.0/10

    private-domain: "hs.liquid.sh"
    domain-insecure: "hs.liquid.sh"

    local-zone: "10.10.in-addr.arpa." nodefault
    local-zone: "hs.liquid.sh." nodefault

    access-control-view: 100.64.0.0/10 tailscale

  stub-zone:
    name: "hs.liquid.sh."
    stub-addr: 10.43.0.50

  stub-zone:
    name: "100.10.10.in-addr.arpa."
    stub-addr: 10.43.0.50

  view:
    name: "tailscale"
    local-zone: "hs.liquid.sh." redirect
    local-data: "hs.liquid.sh. 300 IN A 100.83.180.32"

  forward-zone:
    # Forward all queries (except those in cache and local zone) to
    # upstream recursive servers
    name: "."
    # Queries to this forward zone use TLS
    forward-tls-upstream: yes

    # https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Test+Servers

    # Cloudflare
    forward-addr: 1.1.1.1@853#cloudflare-dns.com
    forward-addr: 1.0.0.1@853#cloudflare-dns.com
    #forward-addr: 2606:4700:4700::1111@853#cloudflare-dns.com
    #forward-addr: 2606:4700:4700::1001@853#cloudflare-dns.com

    # CleanBrowsing
    forward-addr: 185.228.168.9@853#security-filter-dns.cleanbrowsing.org
    forward-addr: 185.228.169.9@853#security-filter-dns.cleanbrowsing.org
    # forward-addr: 2a0d:2a00:1::2@853#security-filter-dns.cleanbrowsing.org
    # forward-addr: 2a0d:2a00:2::2@853#security-filter-dns.cleanbrowsing.org

    # Quad9
    # forward-addr: 9.9.9.9@853#dns.quad9.net
    # forward-addr: 149.112.112.112@853#dns.quad9.net
    # forward-addr: 2620:fe::fe@853#dns.quad9.net
    # forward-addr: 2620:fe::9@853#dns.quad9.net

    # getdnsapi.net
    # forward-addr: 185.49.141.37@853#getdnsapi.net
    # forward-addr: 2a04:b900:0:100::37@853#getdnsapi.net
