apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: apps-homelab
  labels:
    name: radarr
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://homelab-apiserver.tailscale.svc.cluster.local:6443
    namespace: media
  project: homelab
  sources:
    - chart: app-template
      repoURL: https://bjw-s-labs.github.io/helm-charts
      targetRevision: 3.7.3
      helm:
        valueFiles:
          - $values/k8s/homelab/media/radarr/values.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      path: k8s/homelab/media/radarr/resources
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
