---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: homelab
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: PodCIDR
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          # advertise all services
          - { key: somekey, operator: NotIn, values: ["never-used-value"] }
