---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: hubble-ca-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-ca
  namespace: kube-system
spec:
  isCA: true
  commonName: hubble-ca
  secretName: hubble-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: hubble-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: hubble-issuer
  namespace: kube-system
spec:
  ca:
    secretName: hubble-ca-secret
