apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-dangobot
spec:
  instances: 2
  storage:
    storageClass: local-path
    size: 256Mi
  postgresql:
    parameters:
      shared_buffers: '32MB'
      min_wal_size: '10MB' # scaled down from the default of 80 (80 / 8 = 10)
      max_wal_size: '128MB' # scaled down from the default of 1024 (1024 / 8 = 128)
      wal_keep_size: '64MB' # 32 WAL segments * 2MB segment size = 64MB
    synchronous:
      method: any
      number: 1
  bootstrap:
    initdb:
      walSegmentSize: 2 # default is 16
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 128Mi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-homelab
