apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCfajrbMkSoRgmCGewARZ6EO7FGmgqTDKPjnOvjh4NmnxLRDkgGOMdgwyjgc7nxMOyWmhvfQqa1fszyLjiVFdssJU4soYAwN67C9SL7PXHmY9Ob6vy67QYe8/Gch1Eg87v/Iva2c96IFrb0K1fLrPsmf8GEAGPQUoBhg97A7jLeOJFNyrJh/JzS1jmLRKTJ37p7mw3acOe9c7TbR/p9JUneDZlgnoWa7+cVu/2A4eb9WQDeqf91B4KN8H8NuVOvSFLCmNKALehQDmPGgRXENJOd3L6ONMfeAKGEiq8ojGqigc4IajCGqSflEUKskFSggxTTdPn1OM8kRcwK7dVvZZooLO04f2Ok6lkCXeo3cm25CDkmgTHF2L2sfcBmrATzSnvXw9W5V+NKMzys6tRLCswwsKz/SUUPGRzUiYzEEgwzpyM57gfQQxh79nlBImF0MJCQMQAB07yCXrlplct7OEkBIQXwPABXAJlre9G99XaEgts3/TS+L8IFPGEIlHlUFgNz6mgUdxOYluuUWGZLv4xcOGZmQAh0vu/0miXKGFLZvqwOs8JR4PAbEo39WYZpUXeqbuv3xnKDuypI8utIN3Koub1tuufsH8MSbJSIaZuXdEZu8UeAOQaVldrHivm/VSpP/Qw6pKpUtleW1XQzImo4Z61IxQasL7vD4Q175rZ3YDnSK+pfapy2VxoRSgVY96FUnt25K1XFhth9zhbqx4aNUw==
    client_secret: AgBWc9QgrsIpKA0g5FzMCRJixRdGWYAJMnj1Q/WRdEPLcgQxiV7ADxJ4jUaQ+Tbyo+LqcMmXGsp8h56BEE5ZWFHmR1YR7URRnZOQGLmh9y1aj7ljHR+Hby8qpTWWpoPqrHDPGaKrRsPmZmF0ZwpTbbZ4kI2o5SawlDminmvSJawWIiUgtECudIOGS8iFkJV6NhRNv1efKJHHT0ASomUfnJD8Qs3atqKITQOjKv5H1Fd03GwkbDcDNSwUzvhpWlRCH/vyboKy+34smeMMmQ7DpG2CjKoCCTynVyq5yjrjBm1Qs79B3fsEMzjNtsUOJ9OHvcxOdMUJevDai8Zhm+kbUC+3T1e4bZLT3fB39QnJNSrQRSZq/jZpRQqUplhVW6LzVL7X4cCosohfaXHo9aCSlAplRZblwk1B3V8pTjZtRUNu4kfGneTx/8suC0NdnGUJlgLliHN6rCJ1fGK/WLQe4/rKEsU3ww5k+QZ0vtO1mrQoTakyZzEUnc2DBK+xy5DZTYPKMtBrbTPkRc4p8+6jhu/e5cAeHTm3lO0oviEc7DGcA8ThvgEssxor/+BwjkCI61izNN7FMWghDMeYfO3UMQ4CZM6P3aLaADlCak8s7Jw42Wyennx0krOFCWwsjtQ1Tr6qZzik1rezZc3dw9ox4RkQP3UURIeDPgn1gDdr0At6ppFH+vd2uMO3m0PV0PKzBhWzSHwcfxFvYvmri6OkwDPBl6l91/pEEFBLKxYPEo4WpJ7ey2IBuXKQoPtiEfWCVzdfWota5a3GaI8l/MKbrUA=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
