ipam:
  mode: cluster-pool

  operator:
    clusterPoolIPv4PodCIDRList: 10.42.0.0/16
    clusterPoolIPv4MaskSize: 24

kubeProxyReplacement: true
k8sServiceHost: homelab.liquid.sh
k8sServicePort: 6443

bgpControlPlane:
  enabled: true

routingMode: native
ipv4NativeRoutingCIDR: 10.10.0.0/16
enableIPv4Masquerade: false

ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  service:
    annotations:
      tailscale.com/expose: 'true'
      tailscale.com/hostname: cilium-ingress
    type: LoadBalancer
    loadBalancerIP: 10.10.100.11
hubble:
  tls:
    auto:
      enabled: true
      method: certmanager
      certValidityDuration: 1095
      certManagerIssuerRef:
        name: hubble-issuer
        kind: Issuer
        group: cert-manager.io
  relay:
    enabled: true
  ui:
    enabled: true
