ipam:
  mode: cluster-pool

  operator:
    clusterPoolIPv4PodCIDRList: 10.42.0.0/16
    clusterPoolIPv4MaskSize: 24

kubeProxyReplacement: true
k8sServiceHost: homelab.liquid.sh
k8sServicePort: 6443

bgpControlPlane:
  enabled: true

routingMode: native
ipv4NativeRoutingCIDR: 10.10.0.0/16
enableIPv4Masquerade: false
MTU: 1400

# needed for tailscale service ingress
# see: https://tailscale.com/kb/1236/kubernetes-operator#cilium-in-kube-proxy-replacement-mode
#      https://github.com/tailscale/tailscale/issues/11552#issuecomment-2041407250
#      https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#socket-loadbalancer-bypass-in-pod-namespace
socketLB:
  hostNamespaceOnly: true

hubble:
  tls:
    auto:
      enabled: true
      method: certmanager
      certValidityDuration: 1095
      certManagerIssuerRef:
        name: hubble-issuer
        kind: Issuer
        group: cert-manager.io
  relay:
    enabled: true
  ui:
    enabled: true
