apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core
  namespace: apps-homelab
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: core
spec:
  destination:
    namespace: apps-homelab
    server: https://kubernetes.default.svc
  project: homelab
  source:
    path: k8s/homelab/core
    repoURL: https://github.com/LiquidPL/infra.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
