apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: apps-luna
  labels:
    name: argocd
spec:
  project: luna
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 8.5.1
      helm:
        valueFiles:
          - $values/k8s/luna/core/argocd/values.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      path: k8s/luna/core/argocd/resources
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
