apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: apps-luna
  labels:
    name: tailscale
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: luna
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  sources:
    - chart: tailscale-operator
      repoURL: https://pkgs.tailscale.com/helmcharts
      targetRevision: 1.76.1
      helm:
        valueFiles:
          - $values/k8s/luna/core/tailscale/values.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      path: k8s/luna/core/tailscale/resources
      ref: values
  ignoreDifferences:
    - kind: Service
      namespace: tailscale
      name: homelab-apiserver
      jsonPointers:
        - /spec/externalName
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
