installation:
  calicoNetwork:
    bgp: Enabled
    containerIPForwarding: Enabled

    # prevent calico from using tailscale node IPs
    nodeAddressAutodetectionV4:
      skipInterface: tailscale*

    ipPools:
      - cidr: 10.42.0.0/16
        encapsulation: None
  flexVolumePath: /var/lib/rancher/k3s/agent/libexec/kubernetes
