apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-storage
  namespace: media
  labels:
    app.kubernetes.io/name: media
    app.kubernetes.io/instance: media
    media-volume: storage
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Ti
  nfs:
    server: truenas.hs.liquid.sh
    path: "/mnt/pool/media"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
  namespace: media
  labels:
    app.kubernetes.io/name: media
    app.kubernetes.io/instance: media
spec:
  storageClassName: ''
  selector:
    matchLabels:
      app.kubernetes.io/name: media
      app.kubernetes.io/instance: media
      media-volume: storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
