apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico
  namespace: apps-homelab
  labels:
    name: calico
spec:
  project: homelab
  destination:
    server: https://homelab-apiserver.tailscale.svc.cluster.local:6443
    namespace: tigera-operator
  sources:
    - chart: tigera-operator
      repoURL: https://docs.tigera.io/calico/charts
      targetRevision: v3.29.2
      helm:
        valueFiles:
          - $values/k8s/homelab/core/calico/values.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      path: k8s/homelab/core/calico/resources
      ref: values
  ignoreDifferences:
    - group: operator.tigera.io
      kind: Installation
      name: default
      jsonPointers:
        - /spec/calicoNetwork/ipPools
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - ServerSideApply=true
