apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: apps-homelab
  labels:
    name: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  destination:
    server: https://homelab-k8s-operator.lobster-altair.ts.net
    namespace: cert-manager
  sources:
    - chart: cert-manager
      repoURL: quay.io/jetstack/charts
      targetRevision: v1.19.1
      helm:
        valueFiles:
          - $values/k8s/homelab/core/cert-manager/values.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      path: k8s/homelab/core/cert-manager/resources
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
