apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: apps-homelab
  labels:
    name: cilium
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  destination:
    server: https://homelab-k8s-operator.lobster-altair.ts.net
    namespace: kube-system
  sources:
    - chart: cilium
      repoURL: https://helm.cilium.io/
      targetRevision: 1.18.2
      helm:
        valueFiles:
          - $values/k8s/homelab/core/cilium/values.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      path: k8s/homelab/core/cilium/resources
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/audit-version: latest
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/warn-version: latest
    syncOptions:
      - CreateNamespace=true
