
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: apps-homelab
  labels:
    name: cnpg
spec:
  project: homelab
  destination:
    server: https://homelab-apiserver.tailscale.svc.cluster.local:6443
    namespace: cnpg-system
  sources:
    - chart: cloudnative-pg
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.26.0
      helm:
        valuesObject:
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 128Mi
    - repoURL: https://github.com/cloudnative-pg/plugin-barman-cloud.git
      targetRevision: v0.7.0
      path: ./
      directory:
        include: manifest.yaml
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
