apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: apps-homelab
  labels:
    name: monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  destination:
    server: https://homelab-apiserver.tailscale.svc.cluster.local:6443
    namespace: monitoring
  source:
    repoURL: https://github.com/LiquidPL/infra.git
    targetRevision: master
    path: k8s/homelab/core/monitoring/manifests
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
