apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: apps-homelab
  labels:
    name: sealed-secrets
spec:
  project: homelab
  destination:
    server: https://homelab-apiserver.tailscale.svc.cluster.local:6443
    namespace: kube-system
  sources:
    - chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.17.7
      helm:
        valuesObject:
          fullnameOverride: sealed-secrets-controller
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
            limits:
              memory: 64Mi
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
