apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: zfs
  namespace: apps-homelab
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - git:
        repoURL: https://github.com/LiquidPL/infra.git
        revision: master
        directories:
          - path: k8s/homelab/core/zfs/*
          - path: k8s/homelab/core/zfs/resources
            exclude: true
  template:
    metadata:
      name: zfs-{{ .path.basename }}
      namespace: apps-homelab
      labels:
        name: zfs-{{ .path.basename }}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: homelab
      destination:
        server: https://homelab-apiserver.tailscale.svc.cluster.local:6443
        namespace: democratic-csi
      sources:
        - repoURL: https://github.com/LiquidPL/infra.git
          targetRevision: master
          ref: values
        - chart: democratic-csi
          repoURL: ghcr.io/democratic-csi/charts
          targetRevision: 0.15.0
          helm:
            valueFiles:
              - $values/k8s/homelab/core/zfs/values.yaml
              - $values/k8s/homelab/core/zfs/{{ .path.basename }}/values.yaml
      syncPolicy:
        automated:
          selfHeal: true
        retry:
          limit: 3
          backoff:
            duration: 10s
            factor: 3
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zfs-resources
  namespace: apps-homelab
  labels:
    name: zfs-resources
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://homelab-apiserver.tailscale.svc.cluster.local:6443
    namespace: democratic-csi
  project: homelab
  source:
    repoURL: https://github.com/LiquidPL/infra.git
    targetRevision: master
    path: k8s/homelab/core/zfs/resources
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
