apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - secret.yaml
  - service.yaml
  - httproute.yaml
  - networkpolicy.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: glance
  - includeTemplates: true
    pairs:
      app.kubernetes.io/version: v0.8.4
images:
  - name: docker.io/glanceapp/glance
    newTag: v0.8.5@sha256:32ab73d80f2b8b5fb0735b0431deb36b93fbb6b2fb43592449b0178c8b83e350
configMapGenerator:
  - name: glance
    options:
      disableNameSuffixHash: true
    files:
      - ./config/glance.yml
      - ./config/home.yml
