apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: k8s-homelab-operator.lobster-altair.ts.net
  name: k8s-homelab-operator
  namespace: tailscale
spec:
  externalName: placeholder
  type: ExternalName
