apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: homelab-control-plane-1.lobster-altair.ts.net
  name: homelab-apiserver
  namespace: tailscale
spec:
  externalName: placeholder
  type: ExternalName
