apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: homelab-k8s-operator.lobster-altair.ts.net
  name: homelab-k8s-operator
  namespace: tailscale
spec:
  externalName: placeholder
  type: ExternalName
