apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
    jellyfin-volume: media
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 512Gi
  nfs:
    server: truenas.hs.liquid.sh
    path: "/mnt/pool/jellyfin"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
spec:
  storageClassName: ''
  selector:
    matchLabels:
      jellyfin-volume: media
      app.kubernetes.io/name: jellyfin
      app.kubernetes.io/instance: jellyfin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
