apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - serviceaccount.yaml
  - networkpolicy.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: glance-k8s
  - includeTemplates: true
    pairs:
      app.kubernetes.io/version: v0.4.0
images:
  - name: ghcr.io/lukasdietrich/glance-k8s/glance-k8s
    newTag: v0.5.6@sha256:428d9a7096dc1e82c1fda46904718991f2b9cef443f7120f74d93df13509eb47
