apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - serviceaccount.yaml
  - networkpolicy.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: glance-k8s
  - includeTemplates: true
    pairs:
      app.kubernetes.io/version: v0.4.0
images:
  - name: ghcr.io/lukasdietrich/glance-k8s/glance-k8s
    newTag: v0.5.3@sha256:5c9a5f537935f7579de30b544e3f63919f8b1e7e74ba660ecb9fc9fd84b7dd83
