apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - serviceaccount.yaml
  - networkpolicy.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: glance-k8s
  - includeTemplates: true
    pairs:
      app.kubernetes.io/version: v0.4.0
images:
  - name: ghcr.io/lukasdietrich/glance-k8s/glance-k8s
    newTag: v0.5.0@sha256:51ddcb6c73efe1821e5f6933cbb40e103cb8479644f8183053ebbca7d5c39765
