apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-authentik
  namespace: authentik
spec:
  instances: 2
  storage:
    storageClass: local-path
    size: 512Mi
  postgresql:
    parameters:
      shared_buffers: '32MB'
    synchronous:
      method: any
      number: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-homelab
