apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-authentik
  namespace: authentik
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-system-trixie@sha256:0baa26adbbc96de14aa2db976b04e4eaebf568b8541d7bd5f08c223f82980430
  storage:
    storageClass: local-path
    size: 512Mi
  postgresql:
    parameters:
      shared_buffers: '128MB'
    synchronous:
      method: any
      number: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 150m
    limits:
      memory: 512Mi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-homelab
