apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-authentik
  namespace: authentik
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:853438f8efd08a9aa39160d49123d3293ba6988be521c57f370b6155d6c70cac
  storage:
    storageClass: local-path
    size: 512Mi
  postgresql:
    parameters:
      shared_buffers: '128MB'
    synchronous:
      method: any
      number: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 150m
    limits:
      memory: 512Mi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-homelab
