defaultSettings:
  createDefaultDiskLabeledNodes: true
  defaultReplicaCount: '{"v1": "2", "v2": "2"}'
  backupTarget: nfs://truenas.hs.liquid.sh:/mnt/pool/longhorn

persistence:
  defaultClassReplicaCount: 2

ingress:
  enabled: true
  host: longhorn.hs.liquid.sh
  pathType: Prefix
  tls: true
  tlsSecret: tls-longhorn
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

defaultBackupStore:
  backupTarget: s3://longhorn@homelab/
  backupTargetCredentialSecret: s3-secret
