longhornManager:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    node.longhorn.io/create-default-disk: "true"

defaultSettings:
  taintToleration: node-role.kubernetes.io/control-plane:NoSchedule
  systemManagedComponentsNodeSelector: node.longhorn.io/create-default-disk:true
  createDefaultDiskLabeledNodes: true
  defaultReplicaCount: 2
  backupTarget: nfs://truenas.hs.liquid.sh:/mnt/pool/longhorn

persistence:
  defaultClassReplicaCount: 2

csi:
  attacherReplicaCount: 2
  provisionerReplicaCount: 2
  resizerReplicaCount: 2
  snapshotterReplicaCount: 2

ingress:
  enabled: true
  host: longhorn.hs.liquid.sh
  tls: true
  tlsSecret: tls-longhorn
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
