defaultSettings:
  createDefaultDiskLabeledNodes: true
  defaultReplicaCount: '{"v1": "2", "v2": "2"}'

persistence:
  defaultClassReplicaCount: 2

defaultBackupStore:
  backupTarget: s3://longhorn@homelab/
  backupTargetCredentialSecret: s3-secret
