apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: apps-homelab
  labels:
    name: vaultwarden
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://homelab-k8s-operator.lobster-altair.ts.net
    namespace: vaultwarden
  project: homelab
  sources:
    - chart: vaultwarden
      repoURL: ghcr.io/guerzon/vaultwarden
      targetRevision: 0.43.1
      helm:
        valueFiles:
           - $values/k8s/homelab/vaultwarden/values.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      path: k8s/homelab/vaultwarden/resources
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
