apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: apps-luna
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: apps
spec:
  destination:
    namespace: apps-luna
    server: https://kubernetes.default.svc
  project: luna
  source:
    path: k8s/luna/apps
    repoURL: https://github.com/LiquidPL/infra.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
