apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgA6nZOLYxuIZXWYpb7KmuIBstO8UKOUaLio9X5uScm6Q4g9TNbrosCnzEeshvY3wdAYGPBJt0U9X0b9sH2ZfMS43CrVsJ5jw3flqbyFWoU5H+S+mB3elD8bQNRdES+qGG/tVjkucWqaX+7AGsWwmjp2HTQbYqumWcu5zbwe8QfWMvzxoG6xGVltylP71CzIi9xuLo/oyFZuTTMpWx0psCWMwINoX5YgKuaMemLe/mn0Yjxxt2vTlkOm0RE+Up0ZJlAj8nmYifUDaFP4mLkRSlwWbN0IQcc7EoOcR4CU1D1Bp0wKJtJLzgWmVv06shEpjkX6XNQTjmjZPao+rbVssVWm9dMZLt9Xrg+NHo7izsD5fjeD+svF4Len000qvYS6VQ5FB/xX0x6cqDPl94pi0nvCwOdIjnX54oPOgvgHzKCRE689t5sSAd0Lsp7Bb+QduIHmG3PhV2uxS/54y7Szac25SnyiPBwgavglbHe/5Zwe2ZgDShMm65VrfUqQbJT+tPlqfnog3ycFEoVGzPFukkEs8pspf14kLIGUylxwtMCqPZlS14GYlOzvaXOS9EW9nvZTIwYu1ZcxbpkXmV563Kn4PWpL22RVmwzxcu4XNgCiG8b69Jorg06hxJ68TGR60iH3hexDPeL29oI30prkKI02iEKfVU4oe3nF1vszv8VuGx7of8ju+Y5EKuLf1ctOteX+atKnhDkx7PqtVkRfZUhNqw==
    client_secret: AgAjEoVQ2V2I9mt8vSKA2JJA+CnublA4HuIBTx4dqvFUegIXMmuPumAdqAgxh+NRG7N+osRcOudHy4ApbiITuYiot+6BcvybJSUWxC/C3Ht+HYiJEIrd9WmGP4vw1phllU7c2bgSJ2tFM06x9cGVHccH9QW5hHI/q5imf+BSxyl7gJBoK/9K34gVHtQphZuZ84kvK9v8nhXZOaaveCNT0sPY5upouQ3wej1FhJ1qmdFWA+QOXzt5cdV+1NDEL/+fLSHK50XBk7zK94mSF197uZ0f3hDxBQ0LuRGa1NHrYsB3kvqOzT7SW/4zdP6G2ib/n9RzDvB2fEGBBkwm7eX4tiWvWKEY8vYu3Mirrnmwi+YzfQKcQ/j8ZBg5Xx31VxiT7lnWFDeuIPHH1VCTUpj2g9j9OOtRI//KpS6wYGrPP4lNxQNChAeixNjGao8eqiTpfzoFm5P94JPMvzJJDj89E9ZjdbiyPNut8D/W8spVs1KQLMEgwd4gAY3SVdG0mxBBCBnRAOmBCuM9KyXgpSd32HaGazWOsmurRZh2iigJ8uaUDDBtXkf5kqwMKHMvTCOiKYTGwrO1g1wtPuPi1EFvFcPTwwNAHG7w3ixMlRhw23Dbrnv7kQqiXxzsTm7myHFUp3sadzQ1n5gkqK2SdZirvpaxzw2rB/qEZ3EOnTnAfQQPfDSmkvnqceABHvstaXk7XhCCv6Z5R59ZWX+NMpKPqbWC9lytkjGC+VlywQLX9Ulbwz4DPQ4q7Y0O5iFFBsvomJrNLo9/MbiEavtpB2UIR/Y=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
