ARG TAG
ARG BUILDPLATFORM
ARG TARGETPLATFORM

FROM --platform=${TARGETPLATFORM} docker.io/democraticcsi/democratic-csi:${TAG} AS base

FROM --platform=${BUILDPLATFORM} docker.io/alpine:latest AS work

COPY --from=base /home/csi/app /tmp/app/
ADD ./01-env-vars.patch /tmp/app
WORKDIR /tmp/app

RUN apk add patch
RUN patch -p1 < 01-env-vars.patch
RUN rm 01-env-vars.patch

FROM --platform=${TARGETPLATFORM} docker.io/democraticcsi/democratic-csi:${TAG} AS final

COPY --from=work --chown=csi:csi /tmp/app /home/csi/app/
