image:
  repository: deluan/navidrome
  tag: 0.55.2

env:
  ND_BASEURL: https://navidrome.hs.liquid.sh
  ND_PROMETHEUS_ENABLED: 'true'
  ND_PASSWORDENCRYPTIONKEY:
    valueFrom:
      secretKeyRef:
        name: navidrome
        key: passwordEncryptionKey

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000

service:
  main:
    monitor:
      enabled: true
      endpoints:
        - port: http
          scheme: http
          path: /metrics
          interval: 10s

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: navidrome.hs.liquid.sh
        paths:
          - path: /
    tls:
      - hosts:
          - navidrome.hs.liquid.sh
        secretName: tls-navidrome-ingress

persistence:
  config:
    enabled: true
    storageClass: longhorn
    size: 250Mi
  music:
    enabled: true
    existingClaim: navidrome-media
