apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  nodeToNodeMeshEnabled: false
  asNumber: 64512
  serviceClusterIPs:
    - cidr: 10.43.0.0/16
  serviceLoadBalancerIPs:
    - cidr: 10.10.100.0/24
