apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: router
  annotations:
    argocd.argoproj.io/sync-wave: '100'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  peerIP: 10.10.0.1
  asNumber: 64512
