apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-dns
  namespace: apps-luna
  labels:
    name: custom-dns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: luna
  source:
    repoURL: https://github.com/LiquidPL/infra.git
    targetRevision: master
    path: k8s/luna/core/custom-dns/resources
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
