apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: truenas-api-key
  namespace: democratic-csi
spec:
  encryptedData:
    apiKey: AgCX8iXL6srpVoBo5u5JVQBcnmGCTIXLKpAmCNT5JE6qkalPxR9NuCXBdna0j0URdP4nzB2rtCVaFPRdwgNcn9Ber6iayOf2VjhcT/kXZhfBg9M/7W3CKEGEhjyBsgcugM08RX7xwp8LgnpkPR3mq+V4fCxaB8NXN8doXeFYCtG40Zuqdf3+UhjrFTal95TMUKpYifbRW23z9SpAn6XGFooCYTquo1Wl864uKqi+kh8C4BlWk9YkkJLZ2jVR/xdzMJxrZ0Q5YIgbuDq7yRfU/nc4JTk2TiPwR8RMD7FqkhnPE+FBtEKOysimMDwWAu1CyAtyPl4gSzmanBcAFg86pRrOvfLPsIo3Hf3AqpwAH/7w7u0rLdsXuDLwqu0ngGYAQPtAa0DBEm3QCStj3pXsHz6jCi1OEzbFkqpqmeRusHhsejCjwvjCtuhzjNLhT2dXGEAzap5hbGW/BuXJEhV7smoEAGaT+uBGeDkk8UObMzMRP5E5e344fANGsZajR0NVy6nG+7SZkTfULH2su6a1vOjLbslFdtJemg4RlCxGrVSKpE8HYy0IK0iwmiJiUufJPN3EynrYVM4IJ6zSf3jCSSUJ1v+FnrjxCiJ5L9XVMVLLD0cB5WGq/KvvrfD2LoURhJVi5spGQFdTY/ZTcteeEvE7LCHx2VZWAkU/Eicn+LqmlQzYYbly5Mg3kv3sArP+QsJbtg3PqDRKeEtx2RasGuQ1Hn09P7/3RgDaK02FL6n2kifsjO96kFUqdfh8lvh9LPeeKTZveUqzmTIL0m+8YOrEqR0=
  template:
    metadata:
      creationTimestamp: null
      name: truenas-api-key
      namespace: democratic-csi
    type: Opaque
