domain: hs.liquid.sh
watchedResources:
  - HTTPRoute
filters:
  gatewayClasses:
    - gateway-local
service:
  type: LoadBalancer
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
