domain: hs.liquid.sh
watchedResources:
  - HTTPRoute
filters:
  gatewayClasses:
    - gateway-tailscale
fallthrough:
  enabled: true
zoneFiles:
  - filename: homelab.db
    reload: 1m
    domain: hs.liquid.sh
    fallthrough:
      enabled: true
    contents: |
      $ORIGIN hs.liquid.sh.
      @	60 IN	SOA external-dns-local-k8s-gateway.external-dns.hs.liquid.sh. hostmaster.external-dns-local-k8s-gateway.external-dns.hs.liquid.sh. 12345 7200 1800 86400 60

      homeassistant     IN A    100.79.220.13
      truenas           IN A    100.83.58.81
      minio             IN A    100.83.58.81
      octoprint         IN A    100.68.235.99
service:
  type: LoadBalancer
  loadBalancerClass: tailscale
  annotations:
    tailscale.com/hostname: external-dns
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
