domain: hs.liquid.sh
watchedResources:
  - Ingress
  - Service
  - HTTPRoute
service:
  type: ClusterIP
  clusterIP: 10.43.0.50
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
