apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: apps-homelab
  labels:
    name: frigate
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://homelab-apiserver.tailscale.svc.cluster.local:6443
    namespace: frigate
  project: homelab
  sources:
    - chart: frigate
      repoURL: https://blakeblackshear.github.io/blakeshome-charts/
      targetRevision: 7.8.0
      helm:
        valueFiles:
           - $values/k8s/homelab/apps/frigate/values.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      path: k8s/homelab/apps/frigate/resources
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
