apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkwarden
  namespace: apps-homelab
  labels:
    name: linkwarden
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://homelab-k8s-operator.lobster-altair.ts.net
    namespace: linkwarden
  project: homelab
  sources:
    - chart: app-template
      repoURL: ghcr.io/bjw-s-labs/helm
      targetRevision: 4.4.0
      helm:
        valueFiles:
          - $values/k8s/homelab/apps/linkwarden/values.yaml
    - chart: meilisearch
      repoURL: https://meilisearch.github.io/meilisearch-kubernetes
      targetRevision: 0.17.1
      helm:
        releaseName: meilisearch
        valueFiles:
          - $values/k8s/homelab/apps/linkwarden/values-meilisearch.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      path: k8s/homelab/apps/linkwarden/resources
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
