---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topolvm-add-namespace-label-hook
  labels:
    app.kubernetes.io/name: topolvm
    app.kubernetes.io/instance: topolvm-system-topolvm
    app.kubernetes.io/part-of: topolvm
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
rules:
  - apiGroups: ['']
    resources:
      - namespaces
    resourceNames:
      - kube-system
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topolvm-delete-namespace-label-hook
  labels:
    app.kubernetes.io/name: topolvm
    app.kubernetes.io/instance: topolvm-system-topolvm
    app.kubernetes.io/part-of: topolvm
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
rules:
  - apiGroups: ['']
    resources:
      - namespaces
    resourceNames:
      - kube-system
    verbs:
      - get
      - patch
