---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: topolvm-add-namespace-label-hook
  labels:
    app.kubernetes.io/name: topolvm
    app.kubernetes.io/instance: topolvm-system-topolvm
    app.kubernetes.io/part-of: topolvm
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: topolvm-delete-namespace-label-hook
  labels:
    app.kubernetes.io/name: topolvm
    app.kubernetes.io/instance: topolvm-system-topolvm
    app.kubernetes.io/part-of: topolvm
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
