apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: gateway-local
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        annotations:
          lbipam.cilium.io/sharing-key: sharing-10.10.100.10
          lbipam.cilium.io/sharing-cross-namespace: 'envoy-gateway-system,frigate'
        loadBalancerIP: 10.10.100.10
        externalTrafficPolicy: Cluster
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: gateway-tailscale
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        annotations:
          tailscale.com/hostname: envoy-gateway
        loadBalancerClass: tailscale
        externalTrafficPolicy: Cluster
