apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  encryptedData:
    api-token: AgAFd2QQd7juw4vmuCUktbQ0q+4AK06CGQ4GC1z10MgnrEVtvL/0zKOmGhTOcqrxDF+CijEfp6J/D8fDfODzuziKiq2S3twK3ncPJC/N2IiZb5LoDVi42pjPfGZNQ9dZXtz/lP90amkdlBEUSE8R0BeWWyHgMkGw//vXI4jMlZyrqnEAxd3ji8Y4/pQIc294FZdRJswvQqcYPK49navJCJtqtQ/plyBggto8/XjbNbo9cxiOnnaRbHdI+GU6ZnGh1zsz7EY4iiIVmreIms1H9NPiWTq5uBVG7RXtxurx0oG6FdyC0XXxt0TRfRacM+EfpfkI6d8S6dflsXqAFyHDteVNY6ZqHbaAv/7yLgWd8Lw7nM2rpbduwzVDFONcFSmKiRr4Xwff8B6rOv5UsDKlFmVsUsoAK43/rVCxK83OlxrqkAwPtMIUT/k+3HV6p6B+QIC3ViIqFLlYKq4bxse36mAw7OVXVyEdBfhgX18FiaZf9GdXrJDGaGSmr9d886WR/E/mNQ/StgSA/3ns0qtNMhSuZuuPYxDucAU0TD5P5dXmtmVxtVm9eTbXfQLoG3brpN6T6J22ysn0yTA46hmqWJ9IKXkygMwfhONPviy9EyFmd4DZZbhaQhlEeoKrSBdDrnCuxscVKjxSTXrwjOfn4rWFuRy6avoEFn9cy0YTTERyMrbV1C4p1sM0MA2jycJ/3ryvdYJgn61I5FW5qF7bV2WOfIRUWYYBiyeuTKHxSk/3mDcY3PGVdSui
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "100"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
