apiVersion: v1
kind: Service
metadata:
  name: {{ include "unbound.fullname" . }}
  labels:
    {{- include "unbound.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") (.Values.service.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: dnstcp
      port: {{ .Values.service.port }}
      targetPort: dnstcp
      protocol: TCP
    - name: dnsudp
      port: {{ .Values.service.port }}
      targetPort: dnsudp
      protocol: UDP
  selector:
    {{- include "unbound.selectorLabels" . | nindent 4 }}
