apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ""
    argocd.argoproj.io/sync-wave: "5"
  labels:
    app.kubernetes.io/component: alertmanager-webhook-receiver
    app.kubernetes.io/name: ntfy-receiver
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.4.0
  name: ntfy-receiver
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/component: alertmanager-webhook-receiver
    app.kubernetes.io/name: ntfy-receiver
    app.kubernetes.io/part-of: kube-prometheus
