apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foundryvtt
  namespace: apps-luna
  labels:
    name: foundryvtt
spec:
  project: luna
  destination:
    server: https://kubernetes.default.svc
    namespace: foundryvtt
  sources:
    # - chart: foundry-vtt
    #   repoURL: https://helm.mahahe.it/
    - repoURL: https://github.com/LiquidPL/mahahe-it-helm.git
      path: charts/foundry-vtt
      targetRevision: homelab
      helm:
        valueFiles:
          - $values/k8s/luna/apps/foundryvtt/values.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      path: k8s/luna/apps/foundryvtt/resources
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
