crds:
  enabled: true

resources:
  requests:
    cpu: 5m
    memory: 64Mi
  limits:
    memory: 128Mi

cainjector:
  resources:
    requests:
      cpu: 3m
      memory: 64Mi
    limits:
      memory: 128Mi

webhook:
  resources:
    requests:
      cpu: 5m
      memory: 32Mi
    limits:
      memory: 128Mi
