apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: apps-homelab
  labels:
    name: external-dns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  destination:
    server: https://homelab-apiserver.tailscale.svc.cluster.local:6443
    namespace: network
  sources:
    - chart: k8s-gateway
      repoURL: ghcr.io/k8s-gateway/charts
      targetRevision: 3.1.3
      helm:
        valueFiles:
          - $values/k8s/homelab/network/external-dns/values.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
