apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: apps-homelab
  labels:
    name: traefik
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  destination:
    server: https://homelab-apiserver.tailscale.svc.cluster.local:6443
    namespace: traefik
  sources:
    - chart: traefik-crds
      repoURL: https://traefik.github.io/charts
      targetRevision: 1.9.0
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 36.3.0
      helm:
        skipCrds: true
        valueFiles:
          - $values/k8s/homelab/network/traefik/values.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      path: k8s/homelab/network/traefik/resources
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
