apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lan-dns
  namespace: apps-homelab
  labels:
    name: lan-dns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  destination:
    server: https://homelab-k8s-operator.lobster-altair.ts.net
    namespace: network
  sources:
    - repoURL: https://github.com/LiquidPL/infra.git
      path: charts/unbound
      targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
