---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-secret
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCay6UqSYtO/umJsMQzQ9hPou6DJw0Bo+OuO+XKP5LuxFvsP93WJKk4pkvrmQ4XOHuj+ooee/GqfW1rQOXTn2BbCb+tA6f54yC8jgmsak4+lGsGxnNcUtpSmxEArz6O5dnnNf2Mz1oIogS4dmRn7qdj2gGde9Jg5IO8g+i0SNfrUerQumjy5FwVHy4V0U+t5FP1thiZYlujrb+VfGFl1boCixJrwoZxBbKroIC1FieVjmouDd1biOQ+mk0DD+IrsWRm9lGFlJUg/nfBPWvEDMYHF+GN0KN76XqBpSgsqX4VsN1k0osxW2WI1gU9ns8XWBIMK/NSdhT7ZVO86hUqphXtJOdtPKr9OJR55nAqfUcPRX5AFsQO0k7v5WmpF4BbXGwnAqrcblusVZIDffo1WmwWRr2bTMEc5jShejcNOrT29HZBPE+Zis7tSFQdwhoRjxaevVbglBU7E4IcFD7XoKC/IYtteQq7YzM2xDGq4l23XBRdxYIZU3g/k2Wd1zeZf0yTJSQh5tYy64mx8pfsY9JhCLE2wvcVSVQlJu4ypwJlo9pQf3uP3S6n+W7qEUPRj/OiQXGO0d15TkvhNsmk2CZ5d1oiIPlvMIBpdz4Ft1iF1l//yun6/J6jaqT1wGR23BZ+QNChmhis+ia2F9H8dG43B7RTfHoSQLbGAPmlVzNV/Gf9atlWVEsPhsrI/r73cTsItCTH/K7/cOqwN1l+WYm9nFyodw==
    SECRET_ACCESS_KEY: AgBozjq9RW75BXu1cZ1TVIJzOnAdhY4jucLq2/e8e36brHUj83UOQ9xchxJ4awv/2HZLiz/KVdtWUDgq2xm+7Lw3iVNTrD7oW9r7PmygMXKbczibSXQoWl60/4pznU5ygGaJ2Tg4U/nArotaPWu8Vupf8e7nHeq4l/PKA304goaokg2sD5DCldW4JIYtj2PRfCcFfLEdqAeZRAizbvPIfCWi1aSx+S9FON9WV//au8nqqhA8MvZmYLu20xscVBK4G5Z6Wwo5rlQVqCuWnaBN9ghVjxWbRmX+UNAwEDi1JJH8Ht7kfFRsMyJ3/juaM9JLWXd8qHRACU1AO4aKEpLOKwfPPc48DDcN400zaiTgi38sFzdpdJZS/iEuuQlkD+f7+Z/16jXa3Hlms1UjaufjWLKcJR47zQ+HdGsyNn5scj3UA64LHI76I/K/cc1lVFhMNhBmI4/HMF4kbbAXGVRDgFU/0VMuBcSRlk2kJ2CTMZ1CojzkYvCD6+Ei0K72TzU9giBB6nHMa5wHAE6k9Llz7dLwx9zQMIV8lHe+3EPIq1ixZxOP+sZzf39e2Ri1/kAeQqj6PaOlhm8vZntkj5TTjdqeKjTBNRDyIFSJAtLi/xhuEC+2+H92gIz59oe28vF3qdCtvtYk52eCgOSoW/j+ZEgj1Tb5TR0hyWzOyB0gpj4iLmh6yidlrXEpXu/b6IEYTNuwPOt5j5KXiyqDLXzshxdQsmvU1UlYc5AeWuHz8fFLwxAN/7ZUqpnZ
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-100"
      creationTimestamp: null
      name: s3-secret
      namespace: media
    type: Opaque
