apiVersion: v1
kind: Service
metadata:
  name: rp
  namespace: network
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-network
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: web
      port: 80
      targetPort: web
      protocol: TCP
    - name: websecure
      port: 443
      targetPort: websecure
      protocol: TCP
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-network
