config: |
  auth:
    enabled: true
  tls:
    enabled: false
  mqtt:
    enabled: true
    host: 10.10.0.200
    user: '{FRIGATE_MQTT_USER}'
    password: '{FRIGATE_MQTT_PASSWORD}'
  detectors:
    ov:
      type: openvino
      device: GPU
  model:
    width: 300
    height: 300
    input_tensor: nhwc
    input_pixel_format: bgr
    path: /openvino-model/ssdlite_mobilenet_v2.xml
    labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  go2rtc:
    streams:
      front:
        - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.10.10.11:554/cam/realmonitor?channel=1&subtype=0
      front_sub:
        - ffmpeg:front#video=h264#width=1280#height=720#raw=-fpsmax 5#hardware=vaapi
      back:
        - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.10.10.10:554/cam/realmonitor?channel=1&subtype=0
      back_sub:
        - ffmpeg:back#video=h264#width=1280#height=720#raw=-fpsmax 5#hardware=vaapi
    webrtc:
      candidates:
        - 10.10.100.2:8555
        - 100.68.7.50:8555
        - stun:8555
  ffmpeg:
    hwaccel_args: preset-intel-qsv-h264
  cameras:
    front:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/front
            input_args: preset-rtsp-restream
            roles:
              - record
          - path: rtsp://127.0.0.1:8554/front_sub
            input_args: preset-rtsp-restream
            roles:
              - detect
      detect:
        enabled: true
        width: 1280
        height: 720
      motion:
        mask:
          - 0.753,0.043,0.753,0.08,0.964,0.081,0.963,0.037
          - 0,0.52,0.111,0.618,0.084,0.733,0.088,0.796,0.081,0.896,0.051,0.913,0.021,0.896,0.001,0.864
          - 0.811,0,0.798,0.032,0.791,0.113,0.766,0.156,0.757,0.221,0.757,0.274,0.78,0.258,0.798,0.214,0.825,0.215,0.858,0.232,0.885,0.253,0.88,0.298,0.89,0.347,0.898,0.369,0.891,0.41,0.906,0.441,0.901,0.486,0.912,0.499,0.933,0.471,0.945,0.486,0.944,0.515,0.938,0.546,0.943,0.579,0.962,0.583,0.986,0.621,1,0.662,1,0
      zones:
        street:
          coordinates: 0.145,0.135,0.148,0.221,0.242,0.192,0.373,0.162,0.439,0.152,0.566,0.147,0.645,0.148,0.738,0.155,0.784,0.157,0.862,0.17,0.935,0.193,1,0.209,1,0.159,0.791,0.105,0.696,0.088,0.588,0.073,0.482,0.067,0.397,0.078,0.331,0.09,0.224,0.111
          objects:
            - car
        driveway:
          coordinates: 0.681,0.249,0.645,0.218,0.628,0.194,0.621,0.184,0.623,0.175,0.63,0.168,0.366,0.18,0.403,0.188,0.42,0.208,0.431,0.223,0.443,0.261
        front_yard:
          coordinates: 0.362,0.268,0.763,0.245,1,0.53,1,1,0.723,1
        balcony:
          coordinates: 0.717,0.997,0.245,0.02,0.143,0.036,0.143,0.152,0.144,0.37,0.153,0.566,0.179,0.779,0.209,1
          objects:
            - person
      objects:
        track:
          - person
          - car
      review:
        alerts:
          required_zones:
            - driveway
            - front_yard
            - balcony
        detections:
          required_zones:
            - street
            - front_yard
            - balcony
      record:
        enabled: true
        retain:
          days: 7
          mode: all
        alerts:
          retain:
            days: 30
            mode: active_objects
        detections:
          retain:
            days: 14
            mode: active_objects
    back:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/back
            input_args: preset-rtsp-restream
            roles:
              - record
          - path: rtsp://127.0.0.1:8554/back_sub
            input_args: preset-rtsp-restream
            roles:
              - detect
      detect:
        enabled: true
        width: 1280
        height: 720
      motion:
        mask:
          - 0.754,0.038,0.963,0.036,0.963,0.079,0.753,0.081
          - 1,0.649,0.442,0.575,0.159,0.522,0,0.484,0,0.441,0.234,0.493,0.553,0.549,1,0.615
          - 0.306,0.237,0.324,0.207,0.339,0.216,0.35,0.168,0.369,0.174,0.377,0.187,0.397,0.19,0.412,0.209,0.427,0.235,0.449,0.26,0.44,0.281,0.447,0.303,0.442,0.317,0.439,0.341,0.437,0.379,0.419,0.406,0.403,0.412,0.368,0.406,0.351,0.405,0.337,0.377,0.331,0.338,0.326,0.303,0.303,0.267
          - 0.151,0,0.15,0.067,0.145,0.09,0.162,0.103,0.15,0.131,0.173,0.141,0.149,0.172,0.169,0.206,0.172,0.238,0.151,0.245,0.134,0.258,0.158,0.275,0.166,0.304,0.172,0.332,0.161,0.369,0.148,0.39,0.151,0.431,0.125,0.44,0.114,0.456,0.135,0.469,0.115,0.517,0.118,0.543,0.11,0.588,0.132,0.621,0.143,0.669,0.13,0.708,0.118,0.716,0.095,0.721,0.09,0.744,0.091,0.783,0.076,0.789,0.07,0.815,0.064,0.852,0.048,0.843,0.019,0.803,0,0.772,0,0
          - 0.595,0.39,0.597,0.34,0.612,0.344,0.614,0.32,0.629,0.315,0.633,0.335,0.647,0.334,0.652,0.349,0.661,0.367,0.664,0.384
      record:
        enabled: true
        retain:
          days: 7
          mode: all
        alerts:
          retain:
            days: 30
            mode: active_objects
        detections:
          retain:
            days: 14
            mode: active_objects
image:
  repository: ghcr.io/blakeblackshear/frigate
  tag: 0.15.0
persistence:
  media:
    enabled: true
    size: 650Gi
    storageClass: nfs-csi
    skipuninstall: true
  config:
    enabled: true
    size: 512Mi
    storageClass: longhorn
    skipuninstall: true
    ephemeralWritableConfigYaml: true
securityContext:
  capabilities:
    add:
      - PERFMON
resources:
  limits:
    gpu.intel.com/i915: 1
shmSize: 128Mi
envFromSecrets:
  - frigate-secrets
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: frigate.hs.liquid.sh
      paths:
        - path: "/"
          portName: http-auth
  tls:
    - hosts:
        - frigate.hs.liquid.sh
      secretName: tls-frigate-ingress
