apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lldap
  namespace: apps-luna
  labels:
    name: lldap
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: lldap
  project: luna
  sources:
    - chart: lldap
      repoURL: https://djjudas21.github.io/charts/
      targetRevision: 0.6.0
      helm:
        valueFiles:
          - $values/k8s/luna/auth/lldap/values.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      path: k8s/luna/auth/lldap/resources
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
