name: Build Democratic CSI images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Base image tag'
        required: true
        type: string

jobs:
  build:
    name: Build patched image
    runs-on: ubuntu-24.04
    permissions:
      packages: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Build the image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: democratic-csi
          tags: latest ${{ inputs.tag }}-liquid
          platforms: linux/amd64, linux/arm64
          containerfiles: |
            ./containers/democratic-csi/Containerfile
          context: ./containers/democratic-csi
          build-args: |
            TAG=${{ inputs.tag }}
          extra-args: --pull=always

      - name: Push to GitHub Container Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io/liquidpl
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
